### ISSUE TITLE
How to run simulations

### ISSUE THREAD

**Issue by dwgoon** [jgerardin/persistence-detection#1]
Hello!

Could you please add an example of writing the parameter file (`paramfile`) for running simulations?

In other words, it is somewhat difficult for me to understand and utilize `runSimulations.py`.

**Comment by jgerardin** [comment]
Hi @dwgoon ! thanks for your interest in this project.

Let me preface this by noting that I last looked at the code in 2013.

The current `runSimulations.py` expects a param file for each topology that you want to run. The format of the param file must be:
[header line] <initial input level> <change in input> <node logics> <topology number> <ID to assign first parameter sample>
[body lines] <each row is a list of kcat's and Km's for each link in the topology>

Hopefully "initial input level" and "change in input" are self-explanatory.
"node logics": 0 for OR, 1 for AND, in order A-B-C. For example, if you want OR logic on node A and node C, and AND logic on node C, you would have 0 1 0.
"topology number" is an ID number for the topology.
"ID to assign first parameter sample" I think this is a system for assigning ID number for each parameter set. Probably will be 0.

 The individual parameter rows should be
 kcat1 Km1 kcat2 Km2 ...etc
 where the sign on kcat indicates the direction of regulation of that link (positive kcat: activation; negative kcat: inhibition; 0 kcat: absent). links that are absent MUST have kcat = 0 (cannot just leave unspecified), [and Km for those kcat's will be ignored] <-- incorrect. Correct: The code requires that kcat and Km both are 0 if the link is absent.
 
 You can use the code in [generateTopologies](https://github.com/jgerardin/persistence-detection/blob/master/generateTopologies.py) to enumerate the topologies and logics, and to generate parameter samples, but if you want to create the paramfiles that runSimulations is expecting, you'll need to write some wrapper code to handle that.
 
 I hope this helps. If you'd like to talk more, go ahead and send me an email jgerardin@northwestern.edu and we can set up a call.

**Comment by dwgoon** [comment]
@jgerardin, Thanks for your quick response!

I am going to try running the simulations according to your guide!
