### ISSUE TITLE
Michaelis constant in simulate.cc

### ISSUE THREAD

**Issue by dwgoon** [jgerardin/persistence-detection#2]
In `simualte.cc`, I've found a code snippet below:

```C++
else // node is under AND logic
{
	if (i != 0) // node is not input node
	{
		double in1 = 0, in2 = 0, in3 = 0;
		int sign1 = 1, sign2 = 1, sign3 = 1;
		if (Ks[i * (NUMNODES + 1) + 0] > 0) // if there's regulation by A on node i
		{
			in1 = ks[i * (NUMNODES + 1) + 0] * nodes[0] / (conc[i * (NUMNODES + 1) + 0] + Ks[i * (NUMNODES + 1) + 0] + nodes[0]);
			if (ks[i * (NUMNODES + 1) + 0] < 0)
				sign1 = -1;
		}
```

From my understanding, `Ks` represents Michaelis constant, and it cannot have a sign. 

So, is the code, `Ks[i * (NUMNODES + 1) + 0] > 0` , a typo?
Or, is it just checking whether the corresponding link exists? (i.e., `Ks > 0` equals `Ks != 0`, which means the link exists.)

**Comment by jgerardin** [comment]
The code is just checking whether the link exists. and yes `Ks != 0` should be equivalent.

I wrote in #1 that if `kcat == 0`, the Km value doesn't matter --- but that appears to be incorrect, since the code requires that kcat and Km both are 0 if the link is absent.

**Comment by dwgoon** [comment]
@jgerardin 
Thanks for your quick response despite the study has been a long time.

Now, I understand the code!  :)
